language: node_js
node_js:
  - "6"
after_success:
  - npm install -g codecov
  - ./node_modules/.bin/istanbul cover -x 'test-data/**' -x '*.tests.js' ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec ./index.tests.js ./test-data/load-from-config-folder/index.js && codecov
